services:
  bedrock-chat:
    build: 
      context: .
      args:
        - ADMIN_PASSWORD
    ports:
      - "8501:8501"
    env_file: .env
    environment:
      - ADMIN_USERNAME
      - ADMIN_PASSWORD
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    volumes:
      - ./bedrock-chat:/root/.bedrock-chat
      - ${HOME}/.aws:/root/.aws:ro
    network_mode: host