services:
  bedrock-chat:
    build: 
      context: .
      args:
        - ADMIN_PASSWORD
    ports:
      - "8501:8501"
    env_file: .env
    environment:
      - ADMIN_USERNAME
      - ADMIN_PASSWORD
      - AWS_EC2_METADATA_DISABLED=false
      - AWS_REGION=us-west-2
    volumes:
      - ./bedrock-chat:/root/.bedrock-chat
    network_mode: host