services:
  bedrock-chat:
    build: .
    ports:
      - "8501:8501"
    env_file: .env
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_PROFILE
      - AWS_REGION
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./bedrock-chat:/root/.bedrock-chat
      - ~/.aws:/root/.aws:ro
